import 'leaflet/dist/leaflet.css';
//地図をきれいに表示するのに必要
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
//フォントの調節
import "./globals.css";
//共通のベーススタイルを書いている

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
//Googke Fonts のスタイルを定義

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//アプリ全体のタイトルや説明文を指定

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
